[project]
name = "bord3r"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["pillow>=10.4.0", "pyexiftool>=0.5.6", "tqdm>=4.66.5"]
